server:
  port: 8181
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/techlearn
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhtuanle939@gmail.com
    password: luts nmru gsio ljdv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0